### ISSUE TITLE
`make test` fails in src/semgrep-javascript

### ISSUE THREAD

**Issue by dmitris** [returntocorp/semgrep-grammars#8]
`make test` fails in src/semgrep-javascript - copied the error in 
https://gist.github.com/dmitris/325cb081d205f38f5a29037cb83b81b0
"the complete log" copied to https://gist.github.com/dmitris/722e5a6fb06a98bd00a784fe7d556590

The following tests under `expressions` show as red:
- JSX strings with unescaped newlines
- Optional chaining property access
- Optional chaining array access
- Optional function calls
- The null-coalescing operator
- Assignments
- Anonymous JSX element

**Comment by mjambon** [comment]
Hey @dmitris , I'm sorry I missed the notifications about this.

I'm not sure what was happening for you. I'm currently in the process of simplifying and hardening the setup for integrating tree-sitter languages into semgrep. As a first step, we're moving to semgrep-grammars to being directly part of ocaml-tree-sitter rather than a git submodule.
